### ISSUE TITLE
core and templates

### ISSUE THREAD

**Issue by katalinab95** [keder/togogit-site#19]
Создать корневую папку templates
в этой папке должен быть шаблон base здесь же и бутстрап, в navbar разместить core.index и ссылки на заметки

и шаблон index
Создать приложение core, здесь же сделать вью index и urls(путь пустой), использовать шаблон core.index

По итогу должно выйти шаблон для всех base, здесь же navbar и возможность  перехода на заметки

**Comment by mary-lev** [comment]
Екатерина, я уже сделала это. Если будет время, посмотрите, пожалуйста, мой пул реквест.
